#port
server:
  port: 80
#데이터베이스 설정
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: hr
    password: happy
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    database: oracle
    properties: 
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        strage_engine: innodb
        show_sql: true
        format_sql: true
        user_sql_comments: true
  thymeleaf:
    cache: false
    encoding: utf-8
    prefix: classpath:templates/
    suffix: .html
    mode: HTML
  elasticsearch:
    uris: localhost:9200
# mybatis
